language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  provider: heroku
  api_key:
    secure: sTci8uuCp6LZ+KpcgZbQOUK6loPbEUi4dc6G/7/uI6eYxWAhm2TydSDacQ76tcHdfJiznBeDQUcoAmwcUvNn5ndVlcKO/PRVq5GauhfHOvWYeKuGuDHEMZD47DEB77Gb72IoYD/v6MO2D7MkH9uFKoVBqia6LD0uR2dEg8++z8+rc/SvrtVyYNGBFyGHEe1YVszr1hQNryJk/aQkazpbuuppbYAL03Aiy3ZahZiZqVHvInHpW9grZX9cVaHNjr9cdOqufZXeM1Q9mSdUD51wRFSsObvyfVq6DDq2Fkjg6p+qHUsslSNcrBQ8I7+i3pC/hC39xGFx+T1eSPVU2fRV/AS+RC+fKuy5VYmSiKolJPcaf1r4ICr8FXlAMkYtk1iD8N96PFZ+p3F/m+y1K5wQu0i0rikS5wbZQpe1BwA+pQdplGuxQqs+hov4ICGMAbDpAw+eAS9DldjQPvxPJ8lqq3qff93j5bmyPWgchOUKZkIwaq0SibjMjRGABpL8WY3DHOeUwwsewhV8lRATK5B5Lg0DkmHQSy+JnLMcmJDiH7S8LVfFRTlrgCYBz8eXm3DOYHFpMYHS7qhuyXzeeR8W9xagVGCp2WHru32OcxXjsbYDdhWf8i6sAdUV9EGbelFmLEy7lrhOg7YQmbZlwB2ejR8taca8muHESuRNo2KMwEU=
  app: monster-hunter-app
  on:
    repo: koodilauri/monster-hunter-app-frontend
