language: ruby
rvm:
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx-2
deploy:
  provider: heroku
  api_key:
    secure: bPMjfOoUyc55ceOoYEWvmCexCIzUpQtn5j6wQzplnWw1jXAhhPxzC8+UJPde6PF7q74LUA4sI6vV5k/NcdHhPfKppzN4yKMFMoWBCwffJrSluT3b+gtI/QEf8nOleUXoUPe83wZ+hsT2tzy8iy71md89tW1hxZyDraG5brLcvRVOSUlDxS3BFAvfe6ZjeH3Ya9YashQCSulREBjHdHV2JQGb2Cy1BIIBeM6G33vExIUBV4kiy/fLjmJqLn2kOfYB4wODJcHV58NeA/geoQ140oI41Im4WY4ogmYohFAJxXH1dcSFk/NDCziUALopuiu/sJuqQRSOs5KDQyD3m8Xs7vqMazTBPKYq64INHnWjjZ05zHNo5Vxi5VurWIY/1ZzG/tmRN2WUFo/SXgj7dj5E0LUjxyzyldWeWJDRSTS2dJifT4mJo8Vfki/THPVEpScRvXQRMOxaV6qava78ZJguLdOGd0MYeRDaYdzXsuAa1jeRvvPEBHx4OhnGsuJBJAlpH9s2QvCndW0g119CCbX9mR3CFuy+2zZfVU0f4/opqtoeLK+76wXbyoZXxIPYfC6tFsHEqjg+pHqdHFtahU9pMXYHK57e4awdg2ekxdzFnCKmnhnm7jwzYLuKkaWrkyKEYZLQFFQrRX75nNXLvYM0WJkwZ+K4ABXveFtH6+ZRT2c=
  app: monster-hunter-app
  on:
    repo: koodilauri/monster-hunter-app-frontend
