language: node_js
node_js:
- 6
- 7
deploy:
  provider: heroku
  api_key:
    secure: E35RkCr/3tZqS3SNU7OniQtBQRKWYi3RbitI2T9Hyc1RSKgOUjwa7EgqTB5NpoBHWDlXrfsSKK9J9PQAhmdlnASyEQT4mIk5CMH49eNwPUSPzpPzzz6HpvHyb3jkRrMcneWK+6mIr/i99+3kZ6ygdQXzcxXcl2p38QMWXYGpOe8WKApOKwsDXPCF7V+5AC0TYLBCTk/IXSbprQjNM2px7NxnqS62SZgUpJPzvKGLL4fMwyWD4h5ApNBQwxjpPk11NEp2w9x1coRINVHH2NkeYNLVW0A763YXjYm+u3kK4wdTUrynlgw/lv+wjXZEGi5V6Huv4Ale8TLjfoXhA/Xr8iQ33a8/aUdoh61b5B+bDSBfygHnfked4wyUKKEVA3gm1XBQ8jeiw1ooXD/M6MoZfyJpkiCQ48MwLyqZ77VhWFIKFjN8VVb4FsUOKHvu+sxEumXDl37o+pGX9aBUrb0k7WZXR2BcH6jKvj0v97m+sbCWRIl1fi3hj8mKgZdskZsd8+7d3AQ6zsO7xBsbB4TAk4k+gOcJy12wrX+wx+k9BulyKq2riG+7m65VkfX9L2xdYFh2vd6Gg3kzoEim5aUvCywje/myOLmL3aA2aaE6O6Jg58Xp4jr56f632235j4i0aToi2W8h2RjaKniZszmO/i0R/2sP6BJl4ZNb3Zgyt7Y=
  app: monster-hunter-app
  on:
    repo: koodilauri/monster-hunter-app-frontend
