notifications:
  slack: koodipaja:2N46fXy7krC3EstOfxLn6Lhm
  email: false
language: node_js
node_js:
- 8
after_success:
- npm run build
deploy:
  provider: s3
  access_key_id: AKIAIFOBFA4GTBXTRM5A
  secret_access_key:
    secure: MBsx6oOV0rGdn3O+mIsVVaaVEdu6zomX4zUzFEbhFQyCwGx50FF+X25mmF5nLCgSiMmwc/dnc0ZGQ3L78zALrXKStrCidoDTIfDfu2JSxsENFAowQzDadchAVW+bKkEap205vTWbhbkqzm5sxCPGOLQnh1sf1wNodN5Vn9TrVoio9eeEclgeiRv+hFXHzkIXM0l9Fs0ubZG6JxeT6f/W/tjaXKzKUdiirCJNU67SrFn+4AfrE02ljLB51MwwaGluGKP2ihqU9Hu1pdijwGRN1PaGkxwhfW+r6yDdrTIC6obaSinZRlEPGk+7fsGHkC43yD8NYPyclsnlB3OU8yJbtvgpTCd3DLz9t6OA9aa47BRA9fafSyQUEsZfwma1tEUeEqYmCi6sKD7gfH3rvY6lhxpuLY1UXU/c/w6gD/ITnd3bLzlbh8jttpuSzbne4viRtZlCIc58VIMUgx+jM35RNBBV/SHc+kZORIgr04U5KfmfHLEAUn0/KgoNHik+YbTaoboMB2bWxYU1lNIGhNgh150l0vVeag9J4KmaUl+MdEZ/IB5M6vG2qT9n2dxU4O1Fink0xeLiZJnSI4PhRmQE5C+8PWmajiI+oUxgdTrEwc6wIegGWbBj641vyaURbdN2HaESevpVcHcKTToQW4kUi4KtalEAd5qKLA/HsmLWQnQ=
  bucket: mh-tracker.net
  skip_cleanup: true
  local_dir: build
  acl: bucket_owner_full_control
  region: us-east-1
  on:
    repo: koodilauri/monster-hunter-app-frontend
